name: Pytest Workflow

on: [push, pull_request]  # Trigger the workflow on push and pull requests

jobs:
  pytest_job:
    name: Run Pytest
    runs-on: windows-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: 3.10.4  # Replace "3.x" with the Python version you want to use

      - name: Install dependencies
        run: pip install -r requirements.txt  # Install your project's dependencies

      - name: Run pytest
        run: pytest  # Run pytest command
